apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: frontend
          image: "{{ .Values.registry }}/bess-upf-frontend:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
