apiVersion: v1
kind: Service
metadata:
  name: tcp-listener
  namespace: default
spec:
  selector:
    app: tcp-listener
  type: ClusterIP
  ports:
    - name: tcp
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 2112
      targetPort: 2112
