apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- $secret := lookup "v1" "Secret" .Values.namespace "clickhouse-credentials" }}
  {{- if $secret }}
  password: {{ index $secret.data "password" | b64dec | quote }}
  {{- else }}
  password: {{ randAlphaNum 20 | quote }}
  {{- end }}
