{{- if .Values.global.security.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse
  namespace: {{ .Values.global.namespace | default "bess-upf" }}
automountServiceAccountToken: false
{{- end }}
