# generator-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: tcp-sender
  namespace: default
spec:
  parallelism: 2
  completions: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: sender
          image: xtremevoid/tcp-sender:v2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sender-config
          resources:
            requests:
              cpu: "100m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
