apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitigation
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: mitigation
  template:
    metadata:
      annotations:
        {{- if .Values.global.security.mtls.enabled }}
        linkerd.io/inject: enabled
        {{- end }}
      labels:
        app: mitigation
    spec:
      {{- if .Values.global.security.rbac.enabled }}
      serviceAccountName: mitigation
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: mitigation
          image: "{{ .Values.registry }}/bess-upf-mitigation:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.kafkaBroker | default "redpanda:9092" | quote }}
            - name: API_PORT
              value: {{ .Values.apiPort | default 8081 | quote }}
          ports:
            - containerPort: {{ .Values.apiPort | default 8081 }}
