apiVersion: v1
kind: Service
metadata:
  name: mitigation
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mitigation
  ports:
    - name: http
      port: {{ .Values.apiPort | default 8081 }}
      targetPort: {{ .Values.apiPort | default 8081 }}
