apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-ml-models
  namespace: bess-upf
spec:
  template:
    metadata:
      labels:
        app: deploy-ml-models
    spec:
      containers:
        - name: deployer
          image: ghcr.io/that-geekyguy/bess-upf-serve:local-dev
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/deploy_models.py"]
          env:
            - name: RAY_ADDRESS
              value: "http://bess-upf-serve-head-svc:8265"
      restartPolicy: OnFailure
