#!/usr/bin/env bash
# BESS-UPF AI — unified one-shot launcher (Linux · macOS · Windows Git Bash / WSL)
#
# Does everything from a fresh clone:
#   1  Check prerequisites
#   2  Write .env with working defaults  (skips if already exists)
#   3  Generate dev TLS certificates     (skips if certs already exist)
#   4  Git LFS pull large model files    (skips if already present)
#   5  Detect GPU → pick vLLM or Ollama, size model by VRAM
#   6  Ask: start dev services? (Prometheus + upf-sim + Grafana)
#   7  docker compose up --build -d
#   8  Pull Ollama model on first run    (CPU mode only)
#   9  Print access URLs and credentials
#
# Usage:
#   bash run.sh           # interactive — asks about dev services
#   bash run.sh --dev     # always start dev services, no prompt
#   bash run.sh --no-dev  # skip dev services (external Prometheus / production)
#   bash run.sh --build   # pass extra flags to docker compose up
#
# Windows: run in Git Bash (bundled with Git for Windows) or WSL.
#          For native PowerShell: pwsh run.ps1

set -euo pipefail
cd "$(dirname "$0")"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info() { echo -e "${GREEN}[run]${NC} $*"; }
warn() { echo -e "${YELLOW}[run]${NC} $*"; }
err()  { echo -e "${RED}[run] ERROR:${NC} $*" >&2; }
step() { echo -e "\n${CYAN}── $* ──────────────────────────────────────────────${NC}"; }

# ── Arguments ─────────────────────────────────────────────────────────────────
DEV_ARG=""
EXTRA_ARGS=()
for arg in "$@"; do
    case "$arg" in
        --dev)    DEV_ARG="yes" ;;
        --no-dev) DEV_ARG="no"  ;;
        *)        EXTRA_ARGS+=("$arg") ;;
    esac
done

# ── OS detection ──────────────────────────────────────────────────────────────
OS_RAW="$(uname -s 2>/dev/null || echo Unknown)"
case "$OS_RAW" in
    Linux*)          OS="linux"   ;;
    Darwin*)         OS="macos"   ;;
    MINGW*|MSYS*|CYGWIN*) OS="windows" ;;
    *)               OS="unknown" ;;
esac
info "OS: ${OS_RAW} (${OS})"

# ─────────────────────────────────────────────────────────────────────────────
# 1 — Prerequisites
# ─────────────────────────────────────────────────────────────────────────────
step "1/9  Prerequisites"

need() {
    if ! command -v "$1" &>/dev/null; then
        err "$1 not found.  $2"
        exit 1
    fi
    info "  ✓ $1"
}

need docker  "Install Docker Desktop → https://docs.docker.com/get-docker/"
need openssl "Install OpenSSL.  Windows: bundled with Git for Windows."

if ! docker compose version &>/dev/null; then
    err "docker compose v2 not found. Upgrade Docker Desktop or install the compose plugin."
    exit 1
fi
info "  ✓ docker compose (v2)"

HAS_GIT_LFS=0
if command -v git &>/dev/null && git lfs version &>/dev/null 2>&1; then
    HAS_GIT_LFS=1
    info "  ✓ git lfs"
else
    warn "  git lfs not installed — random_forest.joblib (1.2 GB) won't auto-download."
    warn "  Install: https://git-lfs.github.com  then re-run."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 2 — Generate .env
# ─────────────────────────────────────────────────────────────────────────────
step "2/9  Environment file (.env)"

if [[ -f .env ]]; then
    info ".env exists — skipping."
else
    info "Writing .env with development defaults..."
    # Single-quoted heredoc so dollar signs are literal (no shell expansion).
    cat > .env << 'ENVEOF'
# Generated by run.sh — safe to edit.
# Passwords below are development defaults. Change for production.

# ── VictoriaMetrics ──────────────────────────────────────────────────────────
VM_AUTH_USERNAME=vmadmin
VM_AUTH_PASSWORD=localdev123
VM_RETENTION=12

# ── Prometheus ────────────────────────────────────────────────────────────────
PROMETHEUS_RETENTION=24h
PROMETHEUS_SCRAPE_INTERVAL=15s
PROM_SCRAPE_TARGET=prometheus:9090

# ── MinIO ─────────────────────────────────────────────────────────────────────
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=localdev123
MINIO_EXPORTER_USER=upf-exporter
MINIO_EXPORTER_PASSWORD=localdev123
EXPORT_BUCKET=upf-metrics
EXPORT_LOOKBACK=24h
EXPORT_METRICS=pfcp_sessions_total,port_bytes_count,port_packets_count,port_dropped_count,upf_sim_scenario
LOG_LEVEL=info

# ── Caddy reverse proxy ───────────────────────────────────────────────────────
CADDY_HOSTNAME=localhost
CADDY_ADMIN_USER=admin
# bcrypt hash of "localdev123".  Regenerate:
#   docker run --rm caddy:2.8-alpine caddy hash-password --plaintext 'newpass'
CADDY_ADMIN_PASS_HASH=$2a$14$NKdud2KXF7//qIAX0A.zlOpgewpi69/N5ipDSk5.OKIKJay2kBia6

# ── TLS ───────────────────────────────────────────────────────────────────────
TLS_CERT_FILE=/certs/server.crt
TLS_KEY_FILE=/certs/server.key

# ── Detection service ─────────────────────────────────────────────────────────
DETECTION_POLL_INTERVAL=60s
DETECTION_WINDOW=30m
DETECTION_RETENTION_DAYS=30

# ── LLM — auto-configured by run.sh from GPU detection ────────────────────────
VLLM_MODEL=Qwen/Qwen3-8B
VLLM_MAX_MODEL_LEN=3200
VLLM_GPU_MEM_UTIL=0.90
OLLAMA_MODEL=qwen2.5:3b
OLLAMA_MEMORY_LIMIT=6G
OLLAMA_CPU_LIMIT=4
# HuggingFace token — needed only for GPU/vLLM mode.
# Create at https://huggingface.co/settings/tokens (read-only scope).
HF_TOKEN=CHANGE_ME_hf_token

# ── Analysis service ──────────────────────────────────────────────────────────
ANALYSIS_AUTH_USER=analyst
ANALYSIS_AUTH_PASSWORD=localdev123
VLLM_URL=http://vllm:8000
DETECTION_URL=http://detection:8081
ML_INFER_URL=http://ml-infer:8080
MOMENT_URL=http://moment-sidecar:8083
CHRONOS_URL=http://chronos-sidecar:8084
ANALYSIS_URL=http://analysis:8082
MOMENT_VARIANT=MOMENT-1-large
STL_URL=http://stl-sidecar:8085
MAX_QUERY_RANGE=720h
MIN_STEP=15s
ALLOWLIST_REFRESH_INTERVAL=5m
SESSION_TTL=30m

# ── UPF simulator ─────────────────────────────────────────────────────────────
SIM_URL=http://upf-sim:8090
SIM_NODE_ID=sim-upf-01
SIM_BASE_SESSIONS=1000000
SIM_BYTES_PER_SESSION=5000
SIM_SPIKE_MULTIPLIER=4.0
SIM_RAMP_SECONDS=120

# ── Grafana ───────────────────────────────────────────────────────────────────
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=localdev123

# ── STL sidecar ──────────────────────────────────────────────────────────────
HOLIDAY_COUNTRY=IN
HOLIDAY_SUBDIVISION=
ENVEOF
    info ".env written."
fi

# Load .env into current shell.
# set +u: bcrypt hashes ($2a$14$...) contain $2/$14 which look like positional params to bash -u.
set -a
set +u
# shellcheck disable=SC1091
source .env
set -u
set +a

# ─────────────────────────────────────────────────────────────────────────────
# 3 — Dev TLS certificates
# ─────────────────────────────────────────────────────────────────────────────
step "3/9  Dev TLS certificates"

if [[ -f certs/server.crt && -f certs/server.key ]]; then
    info "Certificates exist — skipping."
else
    info "Generating self-signed certificate for ${CADDY_HOSTNAME:-localhost}..."
    # MSYS_NO_PATHCONV prevents Git Bash from converting /CN=... to a Windows path.
    MSYS_NO_PATHCONV=1 bash scripts/gen-dev-certs.sh
fi

# ─────────────────────────────────────────────────────────────────────────────
# 4 — Git LFS pull (large model files)
# ─────────────────────────────────────────────────────────────────────────────
step "4/9  Model artifacts"

if [[ "$HAS_GIT_LFS" -eq 1 ]]; then
    if [[ ! -f models/random_forest.joblib ]]; then
        info "Pulling models/random_forest.joblib via git lfs..."
        git lfs install --local
        git lfs pull
    else
        info "random_forest.joblib present — skipping lfs pull."
    fi
else
    if [[ ! -f models/random_forest.joblib ]]; then
        warn "random_forest.joblib missing and git lfs unavailable."
        warn "Tier 2 sklearn detection will start in degraded mode."
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# 5 — GPU detection → model selection
# ─────────────────────────────────────────────────────────────────────────────
step "5/9  GPU / LLM selection"

COMPOSE_BASE="-f docker-compose.yml"
DEV_COMPOSE="-f dev/docker-compose.yml"
COMPOSE_FILES="$COMPOSE_BASE"
MODE="cpu"

gpu_available() {
    command -v nvidia-smi &>/dev/null || { warn "nvidia-smi not found."; return 1; }
    nvidia-smi &>/dev/null            || { warn "nvidia-smi failed (driver issue?)."; return 1; }
    docker info 2>/dev/null | grep -qi "nvidia" || {
        warn "GPU found but Docker nvidia runtime not configured."
        [[ "$OS" == "linux" ]] && \
            warn "Fix: sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker" || \
            warn "Fix: enable GPU in Docker Desktop settings and install NVIDIA Container Toolkit."
        return 1
    }
    return 0
}

configure_for_gpu() {
    local vram_mb vram_gb
    vram_mb=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null \
              | head -1 | tr -d ' ')
    vram_gb=$(( vram_mb / 1024 ))
    info "GPU VRAM: ${vram_gb} GB"

    if   (( vram_gb >= 24 )); then
        info "≥ 24 GB → Qwen/Qwen3-14B FP16 (max_len 8192)"
        export VLLM_MODEL="Qwen/Qwen3-14B" VLLM_MAX_MODEL_LEN="8192" VLLM_GPU_MEM_UTIL="0.90"
    elif (( vram_gb >= 13 )); then
        info "13–23 GB → Qwen/Qwen3-8B FP16 (max_len 8192)"
        export VLLM_MODEL="Qwen/Qwen3-8B"  VLLM_MAX_MODEL_LEN="8192" VLLM_GPU_MEM_UTIL="0.90"
    elif (( vram_gb >= 8  )); then
        info "8–12 GB → Qwen/Qwen3-8B INT4 (max_len 3200)"
        export VLLM_MODEL="Qwen/Qwen3-8B"  VLLM_MAX_MODEL_LEN="3200" VLLM_GPU_MEM_UTIL="0.90"
    else
        warn "VRAM ${vram_gb} GB < 8 GB — insufficient for vLLM. Falling back to CPU/Ollama."
        return 1
    fi

    # Prompt for HF_TOKEN if still placeholder (needed to download model weights)
    if [[ "${HF_TOKEN:-CHANGE_ME}" == "CHANGE_ME"* ]]; then
        echo ""
        warn "vLLM needs a HuggingFace token to download model weights."
        read -r -p "[run] Enter HF_TOKEN (or press Enter to fall back to CPU/Ollama): " hf_input
        if [[ -n "${hf_input:-}" ]]; then
            export HF_TOKEN="$hf_input"
            sed -i.bak "s|^HF_TOKEN=.*|HF_TOKEN=${hf_input}|" .env && rm -f .env.bak
            info "HF_TOKEN saved to .env."
        else
            warn "No token provided — falling back to CPU/Ollama."
            return 1
        fi
    fi
}

if gpu_available && configure_for_gpu; then
    MODE="gpu"
    COMPOSE_FILES="${COMPOSE_BASE} -f docker-compose.gpu.yml"
    info "LLM mode: GPU  →  vLLM  model=${VLLM_MODEL}"
else
    MODE="cpu"
    COMPOSE_FILES="${COMPOSE_BASE} -f docker-compose.cpu.yml"
    OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5:3b}"

    if [[ -f /proc/meminfo ]]; then
        total_ram_kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')
        total_ram_gb=$(( total_ram_kb / 1024 / 1024 ))
        info "LLM mode: CPU  →  Ollama  model=${OLLAMA_MODEL}  RAM=${total_ram_gb} GB"
        (( total_ram_gb > 0 && total_ram_gb < 8 )) && \
            warn "Low RAM (${total_ram_gb} GB). Consider OLLAMA_MODEL=qwen2.5:1.5b in .env"
    else
        info "LLM mode: CPU  →  Ollama  model=${OLLAMA_MODEL}"
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# 6 — Dev services
# ─────────────────────────────────────────────────────────────────────────────
step "6/9  Dev services (Prometheus + upf-sim + Grafana)"

if [[ "$DEV_ARG" == "yes" ]]; then
    COMPOSE_FILES="${COMPOSE_FILES} ${DEV_COMPOSE}"
    info "Dev services: enabled (--dev)"
elif [[ "$DEV_ARG" == "no" ]]; then
    info "Dev services: disabled (--no-dev)"
elif [[ -t 0 ]]; then
    echo ""
    echo "  Dev services add: upf-sim (simulated 5G UPF), internal Prometheus, Grafana."
    echo "  Recommended for local testing. Skip for production (uses external Prometheus)."
    echo ""
    read -r -p "[run] Start dev services? [Y/n] " dev_choice
    dev_choice="${dev_choice:-y}"
    if [[ "${dev_choice,,}" == "y" ]]; then
        COMPOSE_FILES="${COMPOSE_FILES} ${DEV_COMPOSE}"
        info "Dev services: enabled"
    else
        info "Dev services: disabled (set PROM_SCRAPE_TARGET=<host>:<port> in .env for external Prometheus)"
    fi
else
    # Non-interactive (pipe/CI) — default to dev services on
    COMPOSE_FILES="${COMPOSE_FILES} ${DEV_COMPOSE}"
    info "Dev services: enabled (non-interactive default)"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 7 — Start stack
# ─────────────────────────────────────────────────────────────────────────────
step "7/9  Starting Docker Compose stack"

info "docker compose ${COMPOSE_FILES} up --build -d"
# shellcheck disable=SC2086
docker compose ${COMPOSE_FILES} up --build -d "${EXTRA_ARGS[@]}"

# ─────────────────────────────────────────────────────────────────────────────
# 8 — Ollama model pull  (CPU mode only)
# ─────────────────────────────────────────────────────────────────────────────
step "8/9  LLM model"

if [[ "$MODE" == "cpu" ]]; then
    OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5:3b}"
    info "Waiting for Ollama to be ready (up to 2 min)..."
    retries=24
    while (( retries-- > 0 )); do
        # shellcheck disable=SC2086
        docker compose ${COMPOSE_FILES} exec vllm ollama list &>/dev/null 2>&1 && break
        sleep 5
    done
    info "Pulling ${OLLAMA_MODEL} (first run: ~2 GB download)..."
    # shellcheck disable=SC2086
    docker compose ${COMPOSE_FILES} exec vllm ollama pull "${OLLAMA_MODEL}"
    info "Ollama ready."
else
    info "vLLM downloads model weights on first start (~5 GB)."
    info "Track progress: docker compose logs -f vllm"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 9 — Summary
# ─────────────────────────────────────────────────────────────────────────────
step "9/9  Done"

H="${CADDY_HOSTNAME:-localhost}"
VM_PASS="${VM_AUTH_PASSWORD:-localdev123}"
MINIO_PASS="${MINIO_ROOT_PASSWORD:-localdev123}"
GF_PASS="${GRAFANA_ADMIN_PASSWORD:-localdev123}"
API_USER="${ANALYSIS_AUTH_USER:-analyst}"
API_PASS="${ANALYSIS_AUTH_PASSWORD:-localdev123}"

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  BESS-UPF AI — Stack Ready                                  ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
printf "${GREEN}║${NC}  %-26s %s\n" "Dashboard"  "https://${H}"
printf "${GREEN}║${NC}  %-26s %s\n" "VM UI"       "https://${H}/vm/      (admin / ${VM_PASS})"
printf "${GREEN}║${NC}  %-26s %s\n" "MinIO UI"    "https://${H}/minio/   (minioadmin / ${MINIO_PASS})"
printf "${GREEN}║${NC}  %-26s %s\n" "Grafana"     "https://${H}/grafana/ (admin / ${GF_PASS})"
printf "${GREEN}║${NC}  %-26s %s\n" "Chat API"    "POST https://${H}/api/v1/chat"
printf "${GREEN}║${NC}  %-26s %s\n" ""            "Basic-auth: ${API_USER} / ${API_PASS}"
printf "${GREEN}║${NC}  %-26s %s\n" "Diagnostics" "https://${H}/diagnostics"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC}  TLS warning expected (self-signed cert) — click Advanced > Accept"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC}  docker compose logs -f       # stream all logs"
echo -e "${GREEN}║${NC}  docker compose ps            # service status"
echo -e "${GREEN}║${NC}  docker compose down          # stop everything"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
