# BESS-UPF AI — unified one-shot launcher (Windows PowerShell / pwsh)
#
# Does everything from a fresh clone:
#   1  Check prerequisites
#   2  Write .env with working defaults  (skips if already exists)
#   3  Generate dev TLS certificates     (skips if certs already exist)
#   4  Git LFS pull large model files    (skips if already present)
#   5  Detect GPU -> pick vLLM or Ollama, size model by VRAM
#   6  Ask: start dev services? (Prometheus + upf-sim + Grafana)
#   7  docker compose up --build -d
#   8  Pull Ollama model on first run    (CPU mode only)
#   9  Print access URLs and credentials
#
# Usage:
#   pwsh run.ps1           # interactive
#   pwsh run.ps1 -Dev      # always include dev services
#   pwsh run.ps1 -NoDev    # skip dev services (production / external Prometheus)
#
# Linux / macOS / Windows Git Bash: use bash run.sh instead.

param(
    [switch]$Dev,
    [switch]$NoDev,
    [Parameter(ValueFromRemainingArguments)][string[]]$ExtraArgs
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Push-Location $PSScriptRoot

function Info  { Write-Host "[run] $args" -ForegroundColor Green  }
function Warn  { Write-Host "[run] $args" -ForegroundColor Yellow }
function Err   { Write-Host "[run] ERROR: $args" -ForegroundColor Red }
function Step  { Write-Host "`n-- $args ----------------------------------------------------" -ForegroundColor Cyan }

$DevArg = if ($Dev) { 'yes' } elseif ($NoDev) { 'no' } else { '' }

# ─────────────────────────────────────────────────────────────────────────────
# 1 -- Prerequisites
# ─────────────────────────────────────────────────────────────────────────────
Step "1/9  Prerequisites"

function Need($cmd, $hint) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        Err "$cmd not found.  $hint"; exit 1
    }
    Info "  OK $cmd"
}

Need docker  "Install Docker Desktop -> https://docs.docker.com/get-docker/"
Need openssl "Install OpenSSL (bundled with Git for Windows)."

& docker compose version 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) { Err "docker compose v2 not found. Upgrade Docker Desktop."; exit 1 }
Info "  OK docker compose (v2)"

$HasGitLfs = $false
if ((Get-Command git -ErrorAction SilentlyContinue) -and
    ((& git lfs version 2>&1) -match 'git-lfs')) {
    $HasGitLfs = $true; Info "  OK git lfs"
} else {
    Warn "  git lfs not installed -- random_forest.joblib (1.2 GB) won't auto-download."
    Warn "  Install: https://git-lfs.github.com  then re-run."
}

# ─────────────────────────────────────────────────────────────────────────────
# 2 -- Generate .env
# ─────────────────────────────────────────────────────────────────────────────
Step "2/9  Environment file (.env)"

if (Test-Path .env) {
    Info ".env exists -- skipping."
} else {
    Info "Writing .env with development defaults..."
    # bcrypt("localdev123") pre-computed hash for CADDY_ADMIN_PASS_HASH
    $envContent = @'
# Generated by run.ps1 -- safe to edit.
# Passwords below are development defaults. Change for production.

VM_AUTH_USERNAME=vmadmin
VM_AUTH_PASSWORD=localdev123
VM_RETENTION=12
PROMETHEUS_RETENTION=24h
PROMETHEUS_SCRAPE_INTERVAL=15s
PROM_SCRAPE_TARGET=prometheus:9090
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=localdev123
MINIO_EXPORTER_USER=upf-exporter
MINIO_EXPORTER_PASSWORD=localdev123
EXPORT_BUCKET=upf-metrics
EXPORT_LOOKBACK=24h
EXPORT_METRICS=pfcp_sessions_total,port_bytes_count,port_packets_count,port_dropped_count,upf_sim_scenario
LOG_LEVEL=info
CADDY_HOSTNAME=localhost
CADDY_ADMIN_USER=admin
CADDY_ADMIN_PASS_HASH=$2a$14$NKdud2KXF7//qIAX0A.zlOpgewpi69/N5ipDSk5.OKIKJay2kBia6
TLS_CERT_FILE=/certs/server.crt
TLS_KEY_FILE=/certs/server.key
DETECTION_POLL_INTERVAL=60s
DETECTION_WINDOW=30m
DETECTION_RETENTION_DAYS=30
VLLM_MODEL=Qwen/Qwen2.5-7B-Instruct
VLLM_MAX_MODEL_LEN=3200
VLLM_GPU_MEM_UTIL=0.90
OLLAMA_MODEL=qwen2.5:3b
OLLAMA_MEMORY_LIMIT=6G
OLLAMA_CPU_LIMIT=4
HF_TOKEN=CHANGE_ME_hf_token
ANALYSIS_AUTH_USER=analyst
ANALYSIS_AUTH_PASSWORD=localdev123
VLLM_URL=http://vllm:8000
DETECTION_URL=http://detection:8081
ML_INFER_URL=http://ml-infer:8080
MOMENT_URL=http://moment-sidecar:8083
CHRONOS_URL=http://chronos-sidecar:8084
ANALYSIS_URL=http://analysis:8082
MOMENT_VARIANT=MOMENT-1-large
STL_URL=http://stl-sidecar:8085
MAX_QUERY_RANGE=720h
MIN_STEP=15s
ALLOWLIST_REFRESH_INTERVAL=5m
SESSION_TTL=30m
SIM_URL=http://upf-sim:8090
SIM_NODE_ID=sim-upf-01
SIM_BASE_SESSIONS=1000000
SIM_BYTES_PER_SESSION=5000
SIM_SPIKE_MULTIPLIER=4.0
SIM_RAMP_SECONDS=120
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=localdev123
HOLIDAY_COUNTRY=IN
HOLIDAY_SUBDIVISION=
'@
    [System.IO.File]::WriteAllText("$PSScriptRoot\.env", $envContent, [System.Text.Encoding]::UTF8)
    Info ".env written."
}

# Parse .env into hashtable for summary
$EnvVars = @{}
Get-Content .env | Where-Object { $_ -match '^[^#\s].*=.*' } | ForEach-Object {
    $k, $v = $_ -split '=', 2
    $EnvVars[$k.Trim()] = $v.Trim()
}

# ─────────────────────────────────────────────────────────────────────────────
# 3 -- Dev TLS certificates
# ─────────────────────────────────────────────────────────────────────────────
Step "3/9  Dev TLS certificates"

if ((Test-Path 'certs\server.crt') -and (Test-Path 'certs\server.key')) {
    Info "Certificates exist -- skipping."
} else {
    $hostname = if ($EnvVars['CADDY_HOSTNAME']) { $EnvVars['CADDY_HOSTNAME'] } else { 'localhost' }
    Info "Generating self-signed certificate for $hostname..."
    New-Item -ItemType Directory -Force -Path 'certs' | Out-Null
    & openssl req -x509 -newkey rsa:4096 `
        -keyout "certs\server.key" -out "certs\server.crt" `
        -days 365 -nodes `
        -subj "/CN=$hostname/O=BESS-UPF Dev/C=XX" `
        -addext "subjectAltName=DNS:$hostname,DNS:localhost,IP:127.0.0.1"
    Info "Certificates written to certs\"
}

# ─────────────────────────────────────────────────────────────────────────────
# 4 -- Git LFS pull (large model files)
# ─────────────────────────────────────────────────────────────────────────────
Step "4/9  Model artifacts"

if (-not (Test-Path 'models\random_forest.joblib')) {
    Info "Fetching model artifacts from MinIO..."
    & bash scripts/fetch-models.sh models
    if ($LASTEXITCODE -eq 0) {
        Info "Model artifacts fetched."
    } else {
        Warn "MinIO fetch failed -- Tier 2 sklearn/ML detection will start in degraded mode."
        Warn "Ensure the stack is up and run: bash scripts/fetch-models.sh"
    }
} else {
    Info "random_forest.joblib present -- skipping MinIO fetch."
}

# ─────────────────────────────────────────────────────────────────────────────
# 5 -- GPU detection -> model selection
# ─────────────────────────────────────────────────────────────────────────────
Step "5/9  GPU / LLM selection"

$ComposeBase  = @('-f', 'docker-compose.base.yml', '-f', 'docker-compose.core.yml', '-f', 'docker-compose.ml.yml')
$DevCompose   = @('-f', 'dev/docker-compose.yml')
$ComposeFiles = $ComposeBase
$Mode = 'cpu'

function Test-GpuAvailable {
    if (-not (Get-Command nvidia-smi -ErrorAction SilentlyContinue)) { Warn "nvidia-smi not found."; return $false }
    & nvidia-smi 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { Warn "nvidia-smi failed (driver issue?)."; return $false }
    $di = & docker info 2>&1
    if ($di -notmatch 'nvidia') {
        Warn "GPU found but Docker nvidia runtime not configured."
        Warn "Fix: enable GPU support in Docker Desktop settings."
        return $false
    }
    return $true
}

function Set-GpuModel {
    $vramMb = (& nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>$null |
        Select-Object -First 1).Trim()
    $vramGb = [int]([int]$vramMb / 1024)
    Info "GPU VRAM: ${vramGb} GB"
    if ($vramGb -ge 24) {
        Info ">= 24 GB -> Qwen/Qwen3-14B FP16 (max_len 8192)"
        $env:VLLM_MODEL = 'Qwen/Qwen2.5-14B-Instruct'; $env:VLLM_MAX_MODEL_LEN = '8192'; $env:VLLM_GPU_MEM_UTIL = '0.90'
    } elseif ($vramGb -ge 13) {
        Info "13-23 GB -> Qwen/Qwen3-8B FP16 (max_len 8192)"
        $env:VLLM_MODEL = 'Qwen/Qwen2.5-7B-Instruct';  $env:VLLM_MAX_MODEL_LEN = '8192'; $env:VLLM_GPU_MEM_UTIL = '0.90'
    } elseif ($vramGb -ge 8) {
        Info "8-12 GB -> Qwen/Qwen3-8B INT4 (max_len 3200)"
        $env:VLLM_MODEL = 'Qwen/Qwen2.5-7B-Instruct';  $env:VLLM_MAX_MODEL_LEN = '3200'; $env:VLLM_GPU_MEM_UTIL = '0.90'
    } else {
        Warn "VRAM ${vramGb} GB < 8 GB -- falling back to CPU/Ollama."
        return $false
    }
    $hfToken = $EnvVars['HF_TOKEN']
    if (-not $hfToken -or $hfToken -match '^CHANGE_ME') {
        $hfInput = Read-Host "[run] Enter HF_TOKEN for vLLM (or Enter to use CPU/Ollama)"
        if ($hfInput) {
            $env:HF_TOKEN = $hfInput
            (Get-Content .env) -replace '^HF_TOKEN=.*', "HF_TOKEN=$hfInput" | Set-Content .env
            Info "HF_TOKEN saved to .env."
        } else {
            Warn "No token provided -- falling back to CPU/Ollama."; return $false
        }
    }
    return $true
}

if ((Test-GpuAvailable) -and (Set-GpuModel)) {
    $Mode = 'gpu'
    $ComposeFiles = $ComposeBase + @('-f', 'docker-compose.gpu.yml')
    Info "LLM mode: GPU -> vLLM  model=$($env:VLLM_MODEL)"
} else {
    $Mode = 'cpu'
    $ComposeFiles = $ComposeBase + @('-f', 'docker-compose.cpu.yml')
    $ollamaModel = if ($EnvVars['OLLAMA_MODEL']) { $EnvVars['OLLAMA_MODEL'] } else { 'qwen2.5:3b' }
    try { $ramGb = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB) }
    catch { $ramGb = 0 }
    Info "LLM mode: CPU -> Ollama  model=$ollamaModel  RAM=${ramGb} GB"
    if ($ramGb -gt 0 -and $ramGb -lt 8) { Warn "Low RAM (${ramGb} GB). Consider OLLAMA_MODEL=qwen2.5:1.5b" }
}

# ─────────────────────────────────────────────────────────────────────────────
# 6 -- Dev services
# ─────────────────────────────────────────────────────────────────────────────
Step "6/9  Dev services (Prometheus + upf-sim + Grafana)"

if ($DevArg -eq 'yes') {
    $ComposeFiles += $DevCompose; Info "Dev services: enabled (-Dev)"
} elseif ($DevArg -eq 'no') {
    Info "Dev services: disabled (-NoDev)"
} elseif ([Environment]::UserInteractive) {
    Write-Host ""
    Write-Host "  Dev services add: upf-sim (simulated 5G UPF), Prometheus, Grafana."
    Write-Host "  Recommended for local testing. Skip for production (uses external Prometheus)."
    $choice = Read-Host "[run] Start dev services? [Y/n]"
    if (-not $choice -or $choice -match '^[Yy]') {
        $ComposeFiles += $DevCompose; Info "Dev services: enabled"
    } else {
        Info "Dev services: disabled"
    }
} else {
    $ComposeFiles += $DevCompose; Info "Dev services: enabled (non-interactive default)"
}

# ─────────────────────────────────────────────────────────────────────────────
# 7 -- Start stack
# ─────────────────────────────────────────────────────────────────────────────
Step "7/9  Starting Docker Compose stack"

$upCmd = $ComposeFiles + @('up', '--build', '-d') + $ExtraArgs
Info "docker compose $($upCmd -join ' ')"
& docker compose @upCmd

# ─────────────────────────────────────────────────────────────────────────────
# 8 -- Ollama model pull  (CPU mode only)
# ─────────────────────────────────────────────────────────────────────────────
Step "8/9  LLM model"

if ($Mode -eq 'cpu') {
    $ollamaModel = if ($EnvVars['OLLAMA_MODEL']) { $EnvVars['OLLAMA_MODEL'] } else { 'qwen2.5:3b' }
    Info "Waiting for Ollama (up to 2 min)..."
    $retries = 24
    while ($retries-- -gt 0) {
        & docker compose @ComposeFiles exec vllm ollama list 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) { break }
        Start-Sleep 5
    }
    Info "Pulling $ollamaModel (first run: ~2 GB)..."
    & docker compose @ComposeFiles exec vllm ollama pull $ollamaModel
    Info "Ollama ready."
} else {
    Info "vLLM downloads model weights on first start (~5 GB)."
    Info "Track: docker compose logs -f vllm"
}

# ─────────────────────────────────────────────────────────────────────────────
# 9 -- Summary
# ─────────────────────────────────────────────────────────────────────────────
Step "9/9  Done"

$H      = if ($EnvVars['CADDY_HOSTNAME'])        { $EnvVars['CADDY_HOSTNAME'] }        else { 'localhost' }
$VmP    = if ($EnvVars['VM_AUTH_PASSWORD'])       { $EnvVars['VM_AUTH_PASSWORD'] }       else { 'localdev123' }
$MnP    = if ($EnvVars['MINIO_ROOT_PASSWORD'])    { $EnvVars['MINIO_ROOT_PASSWORD'] }    else { 'localdev123' }
$GfP    = if ($EnvVars['GRAFANA_ADMIN_PASSWORD']) { $EnvVars['GRAFANA_ADMIN_PASSWORD'] } else { 'localdev123' }
$AuU    = if ($EnvVars['ANALYSIS_AUTH_USER'])     { $EnvVars['ANALYSIS_AUTH_USER'] }     else { 'analyst' }
$AuP    = if ($EnvVars['ANALYSIS_AUTH_PASSWORD']) { $EnvVars['ANALYSIS_AUTH_PASSWORD'] } else { 'localdev123' }

$g = 'Green'
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor $g
Write-Host "║  BESS-UPF AI -- Stack Ready                                 ║" -ForegroundColor $g
Write-Host "╠══════════════════════════════════════════════════════════════╣" -ForegroundColor $g
Write-Host "║  Dashboard    https://$H"                                     -ForegroundColor $g
Write-Host "║  VM UI        https://$H/vm/      (admin / $VmP)"            -ForegroundColor $g
Write-Host "║  MinIO UI     https://$H/minio/   (minioadmin / $MnP)"       -ForegroundColor $g
Write-Host "║  Grafana      https://$H/grafana/ (admin / $GfP)"            -ForegroundColor $g
Write-Host "║  Chat API     POST https://$H/api/v1/chat"                   -ForegroundColor $g
Write-Host "║               Basic-auth: $AuU / $AuP"                       -ForegroundColor $g
Write-Host "║  Diagnostics  https://$H/diagnostics"                        -ForegroundColor $g
Write-Host "╠══════════════════════════════════════════════════════════════╣" -ForegroundColor $g
Write-Host "║  TLS warning expected (self-signed cert) -- click Advanced > Accept" -ForegroundColor $g
Write-Host "╠══════════════════════════════════════════════════════════════╣" -ForegroundColor $g
Write-Host "║  docker compose logs -f       # stream all logs"             -ForegroundColor $g
Write-Host "║  docker compose ps            # service status"              -ForegroundColor $g
Write-Host "║  docker compose down          # stop everything"             -ForegroundColor $g
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor $g

Pop-Location
