apiVersion: v1
kind: Service
metadata:
  name: serve
  namespace: {{ .Values.namespace }}
spec:
  selector:
    ray.io/cluster: bess-upf-serve
    ray.io/node-type: head
  ports:
    - name: http
      port: 8000
      targetPort: 8000
